### ISSUE TITLE
Error upon tapping Connect with Google.

### ISSUE THREAD

**Issue by hspark15429** [RivaanRanawat/flutter-reddit-clone#18]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4743:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4757:6)
#2      Element.findAncestorWidgetOfExactType (package:flutter/src/widgets/framework.dart:4818:12)
#3      debugCheckHasScaffoldMessenger.<anonymous closure> (package:flutter/src/material/debug.dart:175:17)
#4      debugCheckHasScaffoldMessenger (package:flutter/src/material/debug.dart:187:4)
#5      ScaffoldMessenger.of (package:flutter/src/material/scaffold.dart:146:12)
#6     <…>
Lost connection to device.

**Comment by tanushahaha** [comment]
try using the pop up login instead of the old one coz it has been discontinued
